### ISSUE TITLE
Unable to maintain this project

### ISSUE THREAD

**Issue by microwavesafe** [lvgl/lv_port_pc_vscode#20]
@kisvegabor Under my current workload I am unable to maintain this project / review the pull requests. Is it possible to offer this role to someone else who might be interested? Possibly from the authors of some of the existing pull requests?

There a couple of interesting pull requests that deserve some time spent on them, but realistically I won't get to them this year.

**Comment by kisvegabor** [comment]
Hi,

Thank you for lettig us know. I'll pay more attention to this repo in the future. 

If you don't mind I keep you current permissions in case  you will have some free time to spend here in the future. :relaxed:

**Comment by microwavesafe** [comment]
Please do leave my current permissions, I may well get time in the future!
