### ISSUE TITLE
Is this repo maintained or not?

### ISSUE THREAD

**Issue by ONLYA** [lvgl/lv_port_pc_vscode#27]
I see someone made a v8.1 update two years ago and v8.2 update a year ago. Now I made an update on v8.3 release. 
Mine is just a simple update while they added more supports.

Would someone check, review and merge those requests?

**Comment by kisvegabor** [comment]
Sorry, I missed https://github.com/lvgl/lv_port_pc_vscode/pull/26.
Just commented there.
