### ISSUE TITLE
[Solved] How to use on Arch Linux

### ISSUE THREAD

**Issue by Sandman6z** [lvgl/lv_port_pc_vscode#47]
针对Arch Linux用户，我做了如下操作，能够跑起来Demo：

# 用如下指令代替Ubuntu系apt指令
```
sudo pacman -S sdl2
sudo pacman -S base-devel
sudo pacman -S gcc make
sudo pacman -S libsdl2-devel
sudo pacman -S sdl2_mixer
sudo pacman -S sdl2-devel
```

# VSCode安装
vscode用AUR管理器安装”visual-studio-code-bin“
例如我用paru：
`paru -S visual-studio-code-bin`

git保证项目完整，各模块更新就能跑起来了
![2024-07-10_14-07](https://github.com/lvgl/lv_port_pc_vscode/assets/23134348/4b0a732e-5f89-473c-85c8-a07fe972ea0e)
![2024-07-10_14-08](https://github.com/lvgl/lv_port_pc_vscode/assets/23134348/a36a9979-82b7-453d-8000-762fc5a9d699)

**Comment by kisvegabor** [comment]
Thank you! Could you send a Pull request to update the README?

**Comment by Sandman6z** [comment]
Sorry, kisvegabor.
I forgot that I turned off the prompt in the issue area, I just checked the blog and remembered it, so I'll do it now.😁

**Comment by kisvegabor** [comment]
Thank you! :blush:
