### ISSUE TITLE
Use whit params CMAKE_BUILD_TYPE:STRING=Debug  Cannot building , but change CMAKE_BUILD_TYPE:STRING=Release  build is OK

### ISSUE THREAD

**Issue by jacksonjim** [lvgl/lv_port_pc_vscode#49]
Windows  10  
Msys64 with MinGW 64 
Vscode 
-------------------------------------------------------------------

use whit params CMAKE_BUILD_TYPE:STRING=Debug 
`cmake -DCMAKE_BUILD_TYPE:STRING=Debug . -Bbuild -G "MinGW Makefiles" `

building will show Error: 
ld.exe: cannot find -lasan: No such file or directory
ld.exe: cannot find -lubsan: No such file or directory

Cmake >>> 
`[proc] 执行命令: D:\msys64\mingw64\bin\cmake.EXE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=D:\msys64\mingw64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\msys64\mingw64\bin\g++.exe --no-warn-unused-cli -SE:/workspace/lv_port_pc_vscode -Be:/workspace/lv_port_pc_vscode/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 14.1.0
[cmake] -- The CXX compiler identification is GNU 14.1.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: D:/msys64/mingw64/bin/gcc.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: D:/msys64/mingw64/bin/g++.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- The ASM compiler identification is GNU
[cmake] -- Found assembler: D:/msys64/mingw64/bin/gcc.exe
[cmake] -- Configuring done (1.7s)
[cmake] -- Generating done (0.4s)
[cmake] -- Build files have been written to: E:/workspace/lv_port_pc_vscode/build`

![image](https://github.com/user-attachments/assets/bc2edb11-44a5-4c25-a4ea-cfaccccf592a)

Budilding Error

`[ 99%] Built target lvgl_examples
[ 99%] Building C object CMakeFiles/main.dir/main/src/main.c.obj
[ 99%] Building C object CMakeFiles/main.dir/main/src/mouse_cursor_icon.c.obj
[100%] Linking CXX executable E:\workspace\lv_port_pc_vscode\bin\main.exe
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan: No such file or directory
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lubsan: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\main.dir\build.make:123: E:/workspace/lv_port_pc_vscode/bin/main.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:109: CMakeFiles/main.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2`
![image](https://github.com/user-attachments/assets/f90b5021-ba36-4a9a-bad0-e5b0fd257f7d)

---------------------------------------------------------------------------------------------------------------------------
 **Release is Building successfully** 
`cmake -DCMAKE_BUILD_TYPE:STRING=Release . -Bbuild -G "MinGW Makefiles" `

`[proc] 执行命令: D:\msys64\mingw64\bin\cmake.EXE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=D:\msys64\mingw64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\msys64\mingw64\bin\g++.exe --no-warn-unused-cli -SE:/workspace/lv_port_pc_vscode -Be:/workspace/lv_port_pc_vscode/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 14.1.0
[cmake] -- The CXX compiler identification is GNU 14.1.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: D:/msys64/mingw64/bin/gcc.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: D:/msys64/mingw64/bin/g++.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- The ASM compiler identification is GNU
[cmake] -- Found assembler: D:/msys64/mingw64/bin/gcc.exe
[cmake] -- Configuring done (1.7s)
[cmake] -- Generating done (0.4s)
[cmake] -- Build files have been written to: E:/workspace/lv_port_pc_vscode/build`

![image](https://github.com/user-attachments/assets/9619d886-97d7-4c89-a40d-8f6a9d19c852)
Buidling successfully

`[ 95%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/roller/lv_example_roller_2.c.obj
[ 95%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/roller/lv_example_roller_3.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/scale/lv_example_scale_1.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/scale/lv_example_scale_2.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/scale/lv_example_scale_3.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/scale/lv_example_scale_4.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/scale/lv_example_scale_5.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/scale/lv_example_scale_6.c.obj
[ 96%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/slider/lv_example_slider_1.c.obj
[ 97%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/slider/lv_example_slider_2.c.obj
[ 97%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/slider/lv_example_slider_3.c.obj
[ 97%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/slider/lv_example_slider_4.c.obj
[ 97%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/span/lv_example_span_1.c.obj
[ 97%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/spinbox/lv_example_spinbox_1.c.obj
[ 97%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/spinner/lv_example_spinner_1.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/switch/lv_example_switch_1.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/table/lv_example_table_1.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/table/lv_example_table_2.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/tabview/lv_example_tabview_1.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/tabview/lv_example_tabview_2.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/textarea/lv_example_textarea_1.c.obj
[ 98%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/textarea/lv_example_textarea_2.c.obj
[ 99%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/textarea/lv_example_textarea_3.c.obj
[ 99%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/tileview/lv_example_tileview_1.c.obj
[ 99%] Building C object lvgl/CMakeFiles/lvgl_examples.dir/examples/widgets/win/lv_example_win_1.c.obj
[ 99%] Linking C static library ..\lib\liblvgl_examples.a
[ 99%] Built target lvgl_examples
[ 99%] Building C object CMakeFiles/main.dir/main/src/main.c.obj
[ 99%] Building C object CMakeFiles/main.dir/main/src/mouse_cursor_icon.c.obj
[100%] Linking CXX executable E:\workspace\lv_port_pc_vscode\bin\main.exe
[100%] Built target main`

![image](https://github.com/user-attachments/assets/8684f50e-66c9-4d60-9337-30cf05e1dc30)

**The demo runs successfully**

![image](https://github.com/user-attachments/assets/a1154aa9-5972-47ce-b721-a82fcd381b21)

Debug & Release diff config 
![image](https://github.com/user-attachments/assets/f303cfeb-8be2-4bb1-8866-ae8dede84a8e)

**Comment by kisvegabor** [comment]
"Asan" might not be available in Windows.  Just remove `-fsanitize=address,leak,undefined` from [here](https://github.com/lvgl/lv_port_pc_vscode/blob/master/CMakeLists.txt#L95C41-L96).
