### ISSUE TITLE
lv_port_pc_vscode/bin/main doesn't exist

### ISSUE THREAD

**Issue by atheeralattar** [lvgl/lv_port_pc_vscode#63]
I am getting this error when I try to debug on linux following the steps in the repo. I can't see 'bin' folder in the repo, is this folder going to be generated after the CMake, this is a totally new area for me so I am just starting.

**Comment by mxsteini** [comment]
@atheeralattar I did it by removing the RTOS in CMakeLists.txt from 0a8220a874da37a582327d7ffd1eeef3fab64c3f.

**Comment by atheeralattar** [comment]
Returned back to [bbb4c82](https://github.com/lvgl/lv_port_pc_vscode/tree/bbb4c82266a7ede61a04070cbef95f7bc0a9561c) which is the previous commit from the one above, everything seems to work now, thanks!

**Comment by kisvegabor** [comment]
@MootSeeker 
I could reproduce the issue like this:
```
mkdir build
cd build
cmake ..
make -j
```

And got 
```
/usr/bin/ld: CMakeFiles/main.dir/FreeRTOS/portable/MemMang/heap_4.c.o: in function `pvPortMalloc':
heap_4.c:(.text+0x22f): undefined reference to `vApplicationMallocFailedHook'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:294: ../bin/main] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Could you take a look at it?

**Comment by MootSeeker** [comment]
@kisvegabor I will take a look at this. I would guess that the CMake file needs to be adjusted to avoid compiling the RTOS part if it is not used.

**Comment by kisvegabor** [comment]
Thank you for the quick action! 
@atheeralattar @mxsteini It worked on my end, could you also try it out?

**Comment by mxsteini** [comment]
@MootSeeker Works like a charms. Thanx for fixing.

**Comment by kisvegabor** [comment]
Cool!
